import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Processor Architecture and Design - Practice Test 2","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/Processor-Architecture-and-Design/Practice-Test-2.md","filePath":"notes/first-semester/Processor-Architecture-and-Design/Practice-Test-2.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/Processor-Architecture-and-Design/Practice-Test-2.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="processor-architecture-and-design-practice-test-2" tabindex="-1">Processor Architecture and Design - Practice Test 2 <a class="header-anchor" href="#processor-architecture-and-design-practice-test-2" aria-label="Permalink to &quot;Processor Architecture and Design - Practice Test 2&quot;">​</a></h1><h2 id="section-a-objective-questions" tabindex="-1">Section A - Objective Questions <a class="header-anchor" href="#section-a-objective-questions" aria-label="Permalink to &quot;Section A - Objective Questions&quot;">​</a></h2><ol><li>What is the fastest level in the memory hierarchy?</li><li>Which memory technology typically requires refresh?</li><li>What does forwarding reduce in a pipeline?</li><li>What is the binary form of a processor instruction called?</li><li>What do we call the address of the next instruction?</li></ol><h2 id="section-b-application-questions" tabindex="-1">Section B - Application Questions <a class="header-anchor" href="#section-b-application-questions" aria-label="Permalink to &quot;Section B - Application Questions&quot;">​</a></h2><ol start="6"><li>A cache has hit time 2 ns, miss rate 4 percent, and miss penalty 25 ns. Find AMAT.</li><li>Why is the data bus bidirectional?</li><li>State two features of ARM.</li><li>Explain one advantage of pipelining.</li><li>Explain one reason why microprogrammed control is preferred in some designs.</li></ol><h2 id="section-c-review-questions" tabindex="-1">Section C - Review Questions <a class="header-anchor" href="#section-c-review-questions" aria-label="Permalink to &quot;Section C - Review Questions&quot;">​</a></h2><ol start="11"><li>What is the difference between datapath and control unit?</li><li>What are the three main cache miss types?</li><li>What is the stored-program idea?</li></ol><h2 id="answer-key" tabindex="-1">Answer Key <a class="header-anchor" href="#answer-key" aria-label="Permalink to &quot;Answer Key&quot;">​</a></h2><ol><li>Registers or cache, depending on the level being compared; in general registers are the fastest.</li><li>DRAM.</li><li>Data hazards and some stall delays.</li><li>Machine language.</li><li>PC.</li><li><code>2 + 0.04 x 25 = 3 ns</code></li><li>Because data must flow from memory to CPU and from CPU to memory.</li><li>Any two: low power, load-store design, RISC style, fixed-length instructions, efficiency.</li><li>Higher throughput because multiple instructions overlap.</li><li>It is easier to modify and extend.</li><li>Datapath moves and transforms data; control unit generates signals and sequences operations.</li><li>Compulsory, capacity, conflict.</li><li>Program and data are stored together in the same memory.</li></ol></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/Processor-Architecture-and-Design/Practice-Test-2.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const PracticeTest2 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  PracticeTest2 as default
};
