import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Module 5 Article: Pipelining — The Assembly Line Processor","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/Processor-Architecture-and-Design/Articles/Module-5-Article.md","filePath":"notes/first-semester/Processor-Architecture-and-Design/Articles/Module-5-Article.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/Processor-Architecture-and-Design/Articles/Module-5-Article.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="module-5-article-pipelining-—-the-assembly-line-processor" tabindex="-1">Module 5 Article: Pipelining — The Assembly Line Processor <a class="header-anchor" href="#module-5-article-pipelining-—-the-assembly-line-processor" aria-label="Permalink to &quot;Module 5 Article: Pipelining — The Assembly Line Processor&quot;">​</a></h1><h2 id="the-big-idea" tabindex="-1">The big idea <a class="header-anchor" href="#the-big-idea" aria-label="Permalink to &quot;The big idea&quot;">​</a></h2><p>A single instruction, step by step, is slow. But many instructions are all doing different steps at once — so why not run them like an <strong>assembly line</strong>? That is exactly what <strong>pipelining</strong> does: split execution into fixed stages and overlap different instructions through those stages. Throughput rises, even though any one instruction still takes the full number of stages.</p><h2 id="the-classic-5-stage-risc-pipeline" tabindex="-1">The classic 5-stage RISC pipeline <a class="header-anchor" href="#the-classic-5-stage-risc-pipeline" aria-label="Permalink to &quot;The classic 5-stage RISC pipeline&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Stage   | What happens                    | Typical work</span></span>
<span class="line"><span>IF      | Fetch instruction               | IR ← MEM[PC]</span></span>
<span class="line"><span>ID      | Decode + read registers         | read rs, rt</span></span>
<span class="line"><span>EX      | Execute / address calculation   | ALU op</span></span>
<span class="line"><span>MEM     | Memory access                   | load/store data</span></span>
<span class="line"><span>WB      | Write result back to a register | write rd/rt</span></span></code></pre></div><p>With a full pipeline, one instruction finishes every cycle (in the ideal case), even though each individual instruction is five cycles &quot;in flight.&quot;</p><h2 id="why-pipelining-is-not-a-free-lunch" tabindex="-1">Why pipelining is not a free lunch <a class="header-anchor" href="#why-pipelining-is-not-a-free-lunch" aria-label="Permalink to &quot;Why pipelining is not a free lunch&quot;">​</a></h2><p>The <strong>ideal speedup</strong> for an N-stage pipeline is <strong>N×</strong>, but three things cut into it:</p><ol><li>Not every stage takes the same time (the cycle is set by the slowest stage).</li><li><strong>Stalls</strong> insert empty &quot;bubble&quot; cycles.</li><li><strong>Branch mispredictions</strong> flush the pipeline.</li></ol><p>So real CPI &gt; 1, and speedup &lt; N.</p><h2 id="pipeline-registers-and-the-stall" tabindex="-1">Pipeline registers and the stall <a class="header-anchor" href="#pipeline-registers-and-the-stall" aria-label="Permalink to &quot;Pipeline registers and the stall&quot;">​</a></h2><p>Between stages sit <strong>pipeline registers</strong> (IF/ID, ID/EX, EX/MEM, MEM/WB). They hold the intermediate state so each stage can run independently every cycle. When a stage cannot proceed (operand missing), it inserts a <strong>bubble</strong> (NOP), stalling that one stage.</p><h2 id="hazards-resolved" tabindex="-1">Hazards, resolved <a class="header-anchor" href="#hazards-resolved" aria-label="Permalink to &quot;Hazards, resolved&quot;">​</a></h2><h3 id="structural-hazards" tabindex="-1">Structural hazards <a class="header-anchor" href="#structural-hazards" aria-label="Permalink to &quot;Structural hazards&quot;">​</a></h3><p>Two instructions need the <strong>same hardware</strong> at the same time. Example: one memory system used for both instruction fetch and data access. Fixes: add a second memory (split I/D) or stall.</p><h3 id="data-hazards" tabindex="-1">Data hazards <a class="header-anchor" href="#data-hazards" aria-label="Permalink to &quot;Data hazards&quot;">​</a></h3><p>The instruction needs a result that an earlier instruction hasn&#39;t written yet.</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>LW  R1, 0(R2)      ; load R1</span></span>
<span class="line"><span>ADD R3, R1, R4     ; needs R1 — not ready yet → stall 1 cycle</span></span></code></pre></div><p><strong>Forwarding (bypassing)</strong> solves most by routing the ALU/memory output directly to the next instruction&#39;s input, skipping write-back. It still <strong>can&#39;t</strong> help the load-use case above, because the value isn&#39;t known until MEM, so the load must stall.</p><h3 id="control-hazards" tabindex="-1">Control hazards <a class="header-anchor" href="#control-hazards" aria-label="Permalink to &quot;Control hazards&quot;">​</a></h3><p>Branches break the &quot;fetch the next sequential instruction&quot; assumption.</p><ul><li><strong>Static prediction:</strong> simple rules (e.g., branch not taken).</li><li><strong>Dynamic prediction:</strong> use a 1-bit or 2-bit saturating counter per branch, or global branch history.</li><li><strong>Cost of a miss:</strong> flush the wrongly-fetched instructions (≈ pipeline depth cycles lost).</li></ul><h2 id="throughput-vs-latency" tabindex="-1">Throughput vs latency <a class="header-anchor" href="#throughput-vs-latency" aria-label="Permalink to &quot;Throughput vs latency&quot;">​</a></h2><ul><li><strong>Latency</strong> = time for one instruction (≈ N cycles; pipeline doesn&#39;t reduce it).</li><li><strong>Throughput</strong> = instructions finished per unit time (≈ 1/cycle ideally; pipeline raises it).</li></ul><p>This is the #1 confusion in exams: &quot;Does pipelining make each instruction faster?&quot; Answer: no, but more finish per second.</p><h2 id="worked-example-a-5-instruction-pipeline-timing" tabindex="-1">Worked example: a 5-instruction pipeline timing <a class="header-anchor" href="#worked-example-a-5-instruction-pipeline-timing" aria-label="Permalink to &quot;Worked example: a 5-instruction pipeline timing&quot;">​</a></h2><p>Assume no hazards. Instructions I1..I5:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Cycle   1   2   3   4   5   6   7</span></span>
<span class="line"><span>I1      IF  ID  EX  MEM WB</span></span>
<span class="line"><span>I2          IF  ID  EX  MEM WB</span></span>
<span class="line"><span>I3              IF  ID  EX  MEM WB</span></span>
<span class="line"><span>I4                  IF  ID  EX  MEM WB</span></span>
<span class="line"><span>I5                      IF  ID  EX  MEM WB</span></span></code></pre></div><p>Five instructions complete in 9 cycles instead of 25 — a ~3× speedup even before accounting for hazards.</p><h2 id="exam-angle" tabindex="-1">Exam angle <a class="header-anchor" href="#exam-angle" aria-label="Permalink to &quot;Exam angle&quot;">​</a></h2><p>For a pipelining question:</p><ol><li>Draw the pipeline diagram (instructions across time), marking IF/ID/EX/MEM/WB.</li><li>If there&#39;s a data hazard, show where the bubble goes and whether forwarding helps.</li><li>If there&#39;s a branch, show the flush on a misprediction.</li><li>Compute speedup: <code>(CPI_nonpipe × IC × T) / (CPI_pipe × IC × T)</code>; IC cancels, so it&#39;s about CPI and clock rates.</li></ol><blockquote><p>Tip: always state the difference between <strong>latency</strong> (un-improved) and <strong>throughput</strong> (improved) — examiners reward the distinction.</p></blockquote></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/Processor-Architecture-and-Design/Articles/Module-5-Article.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Module5Article = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Module5Article as default
};
