import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Persistent Data Management — Cheat Sheet","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/persistent-data-management/Cheat-Sheet.md","filePath":"notes/first-semester/persistent-data-management/Cheat-Sheet.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/persistent-data-management/Cheat-Sheet.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="persistent-data-management-—-cheat-sheet" tabindex="-1">Persistent Data Management — Cheat Sheet <a class="header-anchor" href="#persistent-data-management-—-cheat-sheet" aria-label="Permalink to &quot;Persistent Data Management — Cheat Sheet&quot;">​</a></h1><h2 id="keys-and-dependencies" tabindex="-1">Keys and dependencies <a class="header-anchor" href="#keys-and-dependencies" aria-label="Permalink to &quot;Keys and dependencies&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Super key      = unique attribute set</span></span>
<span class="line"><span>Candidate key  = minimal super key</span></span>
<span class="line"><span>Primary key    = selected candidate key</span></span>
<span class="line"><span>Foreign key    = references a candidate/primary key</span></span>
<span class="line"><span>X → Y          = X functionally determines Y</span></span>
<span class="line"><span>X ↠ Y          = Y varies independently for a fixed X</span></span>
<span class="line"><span>X+             = closure of X under a set of FDs</span></span></code></pre></div><h2 id="normal-forms" tabindex="-1">Normal forms <a class="header-anchor" href="#normal-forms" aria-label="Permalink to &quot;Normal forms&quot;">​</a></h2><table tabindex="0"><thead><tr><th>NF</th><th>One-line test</th></tr></thead><tbody><tr><td>1NF</td><td>Atomic cells; no repeating groups</td></tr><tr><td>2NF</td><td>1NF + no partial dependency of non-prime attribute</td></tr><tr><td>3NF</td><td><code>X→A</code>: X super key or A prime</td></tr><tr><td>BCNF</td><td><code>X→Y</code>: X must be a super key</td></tr><tr><td>4NF</td><td><code>X↠Y</code>: X must be a super key</td></tr></tbody></table><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>BCNF ⇒ 3NF ⇒ 2NF ⇒ 1NF</span></span>
<span class="line"><span>4NF additionally handles independent multivalued facts.</span></span></code></pre></div><h2 id="er-mapping" tabindex="-1">ER mapping <a class="header-anchor" href="#er-mapping" aria-label="Permalink to &quot;ER mapping&quot;">​</a></h2><table tabindex="0"><thead><tr><th>ER construct</th><th>Relational mapping</th></tr></thead><tbody><tr><td>Entity</td><td>Table</td></tr><tr><td>Simple attribute</td><td>Column</td></tr><tr><td>Composite attribute</td><td>Component columns</td></tr><tr><td>Multivalued attribute</td><td>New table with owner key</td></tr><tr><td>Weak entity</td><td>Table with owner key + partial key</td></tr><tr><td>1:1</td><td>FK on total-participation side + UNIQUE</td></tr><tr><td>1:M</td><td>FK on M-side</td></tr><tr><td>M:N</td><td>Junction table</td></tr></tbody></table><h2 id="relational-algebra" tabindex="-1">Relational algebra <a class="header-anchor" href="#relational-algebra" aria-label="Permalink to &quot;Relational algebra&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>σpredicate(R)         selection: rows</span></span>
<span class="line"><span>πattributes(R)        projection: columns</span></span>
<span class="line"><span>R ⋈condition S        join</span></span>
<span class="line"><span>R × S                 Cartesian product</span></span>
<span class="line"><span>R ∪ S                 union</span></span>
<span class="line"><span>R − S                 difference</span></span>
<span class="line"><span>R ∩ S                 intersection</span></span>
<span class="line"><span>R ÷ S                 division: “for all”</span></span>
<span class="line"><span>ρNewName(R)           rename</span></span></code></pre></div><h2 id="calculus" tabindex="-1">Calculus <a class="header-anchor" href="#calculus" aria-label="Permalink to &quot;Calculus&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>TRC: { t | P(t) }</span></span>
<span class="line"><span>DRC: { &lt;x1,...,xn&gt; | P(x1,...,xn) }</span></span>
<span class="line"><span>∀x(P→Q) ≡ ¬∃x(P∧¬Q)</span></span></code></pre></div><p>Result/free variables must be range-restricted for safety.</p><h2 id="sql-patterns" tabindex="-1">SQL patterns <a class="header-anchor" href="#sql-patterns" aria-label="Permalink to &quot;SQL patterns&quot;">​</a></h2><div class="language-sql vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">sql</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">-- Group filter</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> DepartmentID, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">COUNT</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">AS</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> n</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Student</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> AdmissionDate </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">&gt;=</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> DATE</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;2026-01-01&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">GROUP BY</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> DepartmentID</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">HAVING</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> COUNT</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">&gt;=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 5</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">-- Not exists</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> s</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">StudentID</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">s</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">Name</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Student s</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> NOT</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> EXISTS</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Enrollment e</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> e</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">StudentID</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> s</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">StudentID</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">);</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">-- Relational division pattern: students taking every course</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> s</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">StudentID</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">s</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">Name</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Student s</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> NOT</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> EXISTS</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Course c</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> NOT</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> EXISTS</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Enrollment e</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> e</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">StudentID</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">s</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">StudentID</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> AND</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> e</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">CourseID</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">c</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">CourseID</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">);</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">-- Conditional aggregation</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> CourseID,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">       COUNT</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">AS</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> total,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">       SUM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">CASE</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> WHEN</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Marks </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">&gt;=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 40</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> THEN</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> ELSE</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 0</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> END</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">AS</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> passed</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Enrollment</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">GROUP BY</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> CourseID;</span></span></code></pre></div><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>SQL logical order:</span></span>
<span class="line"><span>FROM/JOIN → WHERE → GROUP BY → HAVING</span></span>
<span class="line"><span>→ SELECT → DISTINCT → ORDER BY → LIMIT</span></span></code></pre></div><h2 id="index-choice" tabindex="-1">Index choice <a class="header-anchor" href="#index-choice" aria-label="Permalink to &quot;Index choice&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Query</th><th>Likely choice</th></tr></thead><tbody><tr><td><code>key = value</code></td><td>Hash or B+ tree</td></tr><tr><td><code>key BETWEEN a AND b</code></td><td>B+ tree</td></tr><tr><td>Ordered output</td><td>B+ tree</td></tr><tr><td>Frequent low-selectivity filter</td><td>Scan may win</td></tr><tr><td><code>(A=?, B range)</code></td><td>Composite B+ tree <code>(A,B)</code></td></tr></tbody></table><h2 id="join-algorithms" tabindex="-1">Join algorithms <a class="header-anchor" href="#join-algorithms" aria-label="Permalink to &quot;Join algorithms&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Join</th><th>Memory hook</th></tr></thead><tbody><tr><td>Indexed nested loop</td><td>Small outer, indexed inner</td></tr><tr><td>Hash join</td><td>Equality, large unsorted inputs</td></tr><tr><td>Sort-merge</td><td>Sorted inputs or reusable order</td></tr></tbody></table><h2 id="transactions-and-schedules" tabindex="-1">Transactions and schedules <a class="header-anchor" href="#transactions-and-schedules" aria-label="Permalink to &quot;Transactions and schedules&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>ACID = Atomicity, Consistency, Isolation, Durability</span></span>
<span class="line"><span>Conflict = different T, same item, at least one write</span></span>
<span class="line"><span>Precedence graph: cycle → not conflict-serializable</span></span>
<span class="line"><span>Strict ⇒ Cascadeless ⇒ Recoverable</span></span></code></pre></div><table tabindex="0"><thead><tr><th>Operation pair</th><th style="${ssrRenderStyle({ "text-align": "right" })}">Conflict?</th></tr></thead><tbody><tr><td>R–R</td><td style="${ssrRenderStyle({ "text-align": "right" })}">No</td></tr><tr><td>R–W</td><td style="${ssrRenderStyle({ "text-align": "right" })}">Yes</td></tr><tr><td>W–R</td><td style="${ssrRenderStyle({ "text-align": "right" })}">Yes</td></tr><tr><td>W–W</td><td style="${ssrRenderStyle({ "text-align": "right" })}">Yes</td></tr></tbody></table><h2 id="lock-compatibility" tabindex="-1">Lock compatibility <a class="header-anchor" href="#lock-compatibility" aria-label="Permalink to &quot;Lock compatibility&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Requested / held</th><th style="${ssrRenderStyle({ "text-align": "right" })}">S</th><th style="${ssrRenderStyle({ "text-align": "right" })}">X</th></tr></thead><tbody><tr><td>S</td><td style="${ssrRenderStyle({ "text-align": "right" })}">Yes</td><td style="${ssrRenderStyle({ "text-align": "right" })}">No</td></tr><tr><td>X</td><td style="${ssrRenderStyle({ "text-align": "right" })}">No</td><td style="${ssrRenderStyle({ "text-align": "right" })}">No</td></tr></tbody></table><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>2PL: acquire phase → release phase</span></span>
<span class="line"><span>Strict 2PL: X locks held to commit/abort</span></span>
<span class="line"><span>Rigorous 2PL: S and X locks held to commit/abort</span></span>
<span class="line"><span>Wait-for graph cycle = deadlock</span></span></code></pre></div><h2 id="recovery" tabindex="-1">Recovery <a class="header-anchor" href="#recovery" aria-label="Permalink to &quot;Recovery&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>WAL rule 1: log change before data page</span></span>
<span class="line"><span>WAL rule 2: commit log durable before success</span></span>
<span class="line"><span>UNDO uncommitted effects; REDO committed effects when necessary</span></span>
<span class="line"><span>Checkpoint reduces recovery scanning</span></span></code></pre></div><h2 id="distributed-and-big-data" tabindex="-1">Distributed and big data <a class="header-anchor" href="#distributed-and-big-data" aria-label="Permalink to &quot;Distributed and big data&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>2PC: PREPARE/VOTE → DECIDE/COMMIT-ABORT</span></span>
<span class="line"><span>CAP tradeoff: consistency vs availability during partition</span></span>
<span class="line"><span>5Vs: Volume, Velocity, Variety, Veracity, Value</span></span>
<span class="line"><span>HDFS: NameNode metadata + DataNode blocks</span></span>
<span class="line"><span>MapReduce: Map → Shuffle/Sort → Reduce</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/persistent-data-management/Cheat-Sheet.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const CheatSheet = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  CheatSheet as default
};
