import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Processor Architecture and Design — Cheat Sheet","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/Processor-Architecture-and-Design/Cheat-Sheet.md","filePath":"notes/first-semester/Processor-Architecture-and-Design/Cheat-Sheet.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/Processor-Architecture-and-Design/Cheat-Sheet.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="processor-architecture-and-design-—-cheat-sheet" tabindex="-1">Processor Architecture and Design — Cheat Sheet <a class="header-anchor" href="#processor-architecture-and-design-—-cheat-sheet" aria-label="Permalink to &quot;Processor Architecture and Design — Cheat Sheet&quot;">​</a></h1><h2 id="machine-model-minicpu" tabindex="-1">Machine model: MiniCPU <a class="header-anchor" href="#machine-model-minicpu" aria-label="Permalink to &quot;Machine model: MiniCPU&quot;">​</a></h2><ul><li>32-bit, load-store RISC, 16 registers R0–R15 (R0 = constant 0), little-endian.</li><li>Instructions: LDR, STR, ADD, SUB, MUL, BEQ, JMP, MOV, HLT.</li><li>Flags: Z, C, N, V. PC increments by 4.</li></ul><h2 id="instruction-cycle-single-cycle-view" tabindex="-1">Instruction cycle (single-cycle view) <a class="header-anchor" href="#instruction-cycle-single-cycle-view" aria-label="Permalink to &quot;Instruction cycle (single-cycle view)&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>PC → MAR; read MEM[PC] → IR; PC ← PC+4</span></span>
<span class="line"><span>Decode opcode, read register file</span></span>
<span class="line"><span>ALU computes result</span></span>
<span class="line"><span>(optionally) write MEM or write register file</span></span></code></pre></div><h2 id="pipeline-stages" tabindex="-1">Pipeline stages <a class="header-anchor" href="#pipeline-stages" aria-label="Permalink to &quot;Pipeline stages&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>IF  Fetch instruction (IR ← MEM[PC])</span></span>
<span class="line"><span>ID  Decode + read registers</span></span>
<span class="line"><span>EX  ALU operation</span></span>
<span class="line"><span>MEM Access data memory</span></span>
<span class="line"><span>WB  Write result to register</span></span></code></pre></div><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Ideal CPI = 1 instruction/cycle (full pipeline)</span></span>
<span class="line"><span>Non-pipelined CPI ≈ #stages per instruction</span></span></code></pre></div><h2 id="hazards" tabindex="-1">Hazards <a class="header-anchor" href="#hazards" aria-label="Permalink to &quot;Hazards&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Structural  = hardware resource conflict       → add resource or stall</span></span>
<span class="line"><span>Data        = operand not ready                → forwarding or stall</span></span>
<span class="line"><span>Control     = branch target unknown            → predict or delay branch</span></span></code></pre></div><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Load-use stall (no forwarding for load→use):</span></span>
<span class="line"><span>  LW R1,... ; ADD R2,R1,R3   → 1 stall cycle</span></span></code></pre></div><h2 id="branch-prediction" tabindex="-1">Branch prediction <a class="header-anchor" href="#branch-prediction" aria-label="Permalink to &quot;Branch prediction&quot;">​</a></h2><ul><li>Static: always not-taken, or backward=taen.</li><li>2-bit saturating counter: strongly/weakly taken/not-taken.</li><li>Misprediction cost = flush pipeline (≈ #stages cycles lost).</li></ul><h2 id="amat" tabindex="-1">AMAT <a class="header-anchor" href="#amat" aria-label="Permalink to &quot;AMAT&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Average Memory Access Time = Hit Time + Miss Rate × Miss Penalty</span></span>
<span class="line"><span></span></span>
<span class="line"><span>TLB-miss AMAT = t_hit + (1 - TLB_hit_rate) × t_page_walk</span></span></code></pre></div><h2 id="cache" tabindex="-1">Cache <a class="header-anchor" href="#cache" aria-label="Permalink to &quot;Cache&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Cache params: size, block size, associativity</span></span>
<span class="line"><span>Miss types: compulsory, capacity, conflict</span></span>
<span class="line"><span>Write policies: write-through vs write-back; write-allocate vs no-write-allocate</span></span>
<span class="line"><span>Set index = (block_number mod number_of_sets); tag = block_number / sets</span></span>
<span class="line"><span>MESI: Modified, Exclusive, Shared, Invalid</span></span></code></pre></div><h2 id="memory-hierarchy-per-byte-cost-latency" tabindex="-1">Memory hierarchy (per-byte cost, latency) <a class="header-anchor" href="#memory-hierarchy-per-byte-cost-latency" aria-label="Permalink to &quot;Memory hierarchy (per-byte cost, latency)&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Registers &lt; L1 &lt; L2 (&lt; L3) &lt; RAM &lt; SSD &lt; HDD &lt; tape/network</span></span></code></pre></div><h2 id="addressing-translation" tabindex="-1">Addressing &amp; translation <a class="header-anchor" href="#addressing-translation" aria-label="Permalink to &quot;Addressing &amp; translation&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Virtual address:  [ VPN ][ offset ]</span></span>
<span class="line"><span>Physical addr:    [ PFN ][ offset ]</span></span>
<span class="line"><span>Translation:      page table (per process), base register → PT in memory</span></span>
<span class="line"><span>MMU does it per access; TLB caches recent VPN→PFN</span></span>
<span class="line"><span>Protection bits per PTE: P, R/W, X, U/S, dirty, accessed</span></span></code></pre></div><h2 id="risc-vs-cisc" tabindex="-1">RISC vs CISC <a class="header-anchor" href="#risc-vs-cisc" aria-label="Permalink to &quot;RISC vs CISC&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>RISC: load-store, fixed/simple, ~1 CPI, easy pipelining, more instructions</span></span>
<span class="line"><span>CISC: memory-to-memory, variable, complex, microcode, fewer instructions</span></span></code></pre></div><table tabindex="0"><thead><tr><th>ISA</th><th>Type</th><th>Notes</th></tr></thead><tbody><tr><td>x86 / x86-64</td><td>CISC</td><td>Desktop/server</td></tr><tr><td>ARM/AArch64</td><td>RISC</td><td>Mobile → server</td></tr><tr><td>RISC-V</td><td>RISC</td><td>Open/standard</td></tr><tr><td>MIPS</td><td>RISC</td><td>Teaching</td></tr></tbody></table><h2 id="exceptions-interrupts-traps" tabindex="-1">Exceptions, interrupts, traps <a class="header-anchor" href="#exceptions-interrupts-traps" aria-label="Permalink to &quot;Exceptions, interrupts, traps&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Exception (synchronous)  → fault/recoverable, or abort/fatal</span></span>
<span class="line"><span>Interrupt  (asynchronous)  → maskable IRQ / non-maskable NMI</span></span>
<span class="line"><span>Trap       (syscall)       → deliberate, into kernel</span></span>
<span class="line"><span>Flow: finish instr → save PC/flags → kernel mode → vector → ISR → restore</span></span></code></pre></div><h2 id="protection-rings" tabindex="-1">Protection rings <a class="header-anchor" href="#protection-rings" aria-label="Permalink to &quot;Protection rings&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>x86: ring 0 (kernel) → ring 3 (user). Only ring 0 executes privileged I/O.</span></span>
<span class="line"><span>ARM: EL1 (kernel) / EL0 (user).</span></span></code></pre></div><h2 id="system-call-x86-64" tabindex="-1">System call (x86-64) <a class="header-anchor" href="#system-call-x86-64" aria-label="Permalink to &quot;System call (x86-64)&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>mov rax, &lt;number&gt;   ; syscall number</span></span>
<span class="line"><span>mov rdi, &lt;arg1&gt;     ; args in rdi, rsi, rdx, r10, r8, r9</span></span>
<span class="line"><span>syscall             ; enter kernel; result in rax; ret with sysret</span></span></code></pre></div><h2 id="boot" tabindex="-1">Boot <a class="header-anchor" href="#boot" aria-label="Permalink to &quot;Boot&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>BIOS/UEFI → bootloader (GRUB/systemd-boot) → kernel + initrd → /sbin/init (PID 1) → systemd targets</span></span></code></pre></div><h2 id="virtual-memory-notes" tabindex="-1">Virtual memory notes <a class="header-anchor" href="#virtual-memory-notes" aria-label="Permalink to &quot;Virtual memory notes&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Page size typical: 4 KiB. Page table per process.</span></span>
<span class="line"><span>Demand paging: load on first touch.</span></span>
<span class="line"><span>Copy-on-write: share after fork, copy on write.</span></span>
<span class="line"><span>Replacement: LRU approximated via accessed/dirty bits.</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/Processor-Architecture-and-Design/Cheat-Sheet.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const CheatSheet = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  CheatSheet as default
};
