import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Module 13: Protocols and Shared Behavior","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/programming-from-first-principles/Module-13.md","filePath":"notes/first-semester/programming-from-first-principles/Module-13.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/programming-from-first-principles/Module-13.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="module-13-protocols-and-shared-behavior" tabindex="-1">Module 13: Protocols and Shared Behavior <a class="header-anchor" href="#module-13-protocols-and-shared-behavior" aria-label="Permalink to &quot;Module 13: Protocols and Shared Behavior&quot;">​</a></h1><p><a href="./Module-12">← Previous: Module 12</a> · <a href="./README">Subject index</a> · <a href="./Module-14">Next: Module 14 →</a></p><h2 id="learning-outcomes" tabindex="-1">Learning outcomes <a class="header-anchor" href="#learning-outcomes" aria-label="Permalink to &quot;Learning outcomes&quot;">​</a></h2><ul><li>describe shared behavior in Python;</li><li>use <code>Protocol</code> or <code>ABC</code> to state an interface;</li><li>understand duck typing;</li><li>explain why shared behavior is useful.</li></ul><h2 id="prerequisites" tabindex="-1">Prerequisites <a class="header-anchor" href="#prerequisites" aria-label="Permalink to &quot;Prerequisites&quot;">​</a></h2><p>Read <a href="./Module-12">Module 12</a> first. You should be comfortable with step-by-step reasoning about code behavior.</p><h2 id="the-idea-in-one-sentence" tabindex="-1">The idea in one sentence <a class="header-anchor" href="#the-idea-in-one-sentence" aria-label="Permalink to &quot;The idea in one sentence&quot;">​</a></h2><p>Protocols and shared behavior let one piece of code work with many types as long as they support the same operations.</p><h2 id="everyday-analogy" tabindex="-1">Everyday analogy <a class="header-anchor" href="#everyday-analogy" aria-label="Permalink to &quot;Everyday analogy&quot;">​</a></h2><p>Think of different kinds of vehicles. A car and a bus are different, but both can move forward and stop. The behavior matters more than the label.</p><h2 id="syntax" tabindex="-1">Syntax <a class="header-anchor" href="#syntax" aria-label="Permalink to &quot;Syntax&quot;">​</a></h2><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> typing </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Protocol</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">class</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> HasArea</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">Protocol</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> area</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(self) -&gt; </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">float</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">        ...</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> print_area</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(shape: HasArea) -&gt; </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">None</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    print</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(shape.area())</span></span></code></pre></div><h2 id="worked-example" tabindex="-1">Worked example <a class="header-anchor" href="#worked-example" aria-label="Permalink to &quot;Worked example&quot;">​</a></h2><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">class</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> Circle</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    def</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> __init__</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(self, radius):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">        self</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.radius </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> radius</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> area</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(self):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">        return</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 3.14</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> self</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.radius </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> self</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.radius</span></span></code></pre></div><p>Step by step:</p><ol><li><code>Circle</code> has an <code>area()</code> method.</li><li><code>print_area</code> only needs something that supports <code>area()</code>.</li><li>The exact class name matters less than the behavior.</li></ol><h2 id="why-this-matters-in-practice" tabindex="-1">Why this matters in practice <a class="header-anchor" href="#why-this-matters-in-practice" aria-label="Permalink to &quot;Why this matters in practice&quot;">​</a></h2><ul><li>In college notes, this module shows how Python handles shared behavior.</li><li>In real code, it helps you write functions that accept many object types.</li><li>It makes code flexible without forcing everything into one inheritance tree.</li></ul><h2 id="important-concepts" tabindex="-1">Important concepts <a class="header-anchor" href="#important-concepts" aria-label="Permalink to &quot;Important concepts&quot;">​</a></h2><h3 id="duck-typing" tabindex="-1">Duck typing <a class="header-anchor" href="#duck-typing" aria-label="Permalink to &quot;Duck typing&quot;">​</a></h3><p>If an object behaves correctly, it fits.</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> show_area</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(shape):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    print</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(shape.area())</span></span></code></pre></div><h3 id="protocol" tabindex="-1">Protocol <a class="header-anchor" href="#protocol" aria-label="Permalink to &quot;Protocol&quot;">​</a></h3><p>A protocol describes the operations an object must support.</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">class</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> HasArea</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">Protocol</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> area</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(self) -&gt; </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">float</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">        ...</span></span></code></pre></div><h3 id="abc" tabindex="-1">ABC <a class="header-anchor" href="#abc" aria-label="Permalink to &quot;ABC&quot;">​</a></h3><p>An abstract base class is a class meant to define shared behavior for subclasses.</p><h2 id="technical-meaning" tabindex="-1">Technical meaning <a class="header-anchor" href="#technical-meaning" aria-label="Permalink to &quot;Technical meaning&quot;">​</a></h2><p>Shared behavior is a way to write code that works with many types as long as they support the same operations. Python often uses duck typing, while <code>Protocol</code> and <code>ABC</code> let you describe that behavior more explicitly for tools and readers.</p><h2 id="memory-rule" tabindex="-1">Memory rule <a class="header-anchor" href="#memory-rule" aria-label="Permalink to &quot;Memory rule&quot;">​</a></h2><ul><li>protocol = behavior contract</li><li>duck typing = behavior matters more than type name</li><li>ABC = abstract base class</li></ul><h2 id="quick-check" tabindex="-1">Quick check <a class="header-anchor" href="#quick-check" aria-label="Permalink to &quot;Quick check&quot;">​</a></h2><ul><li>What does <code>HasArea</code> describe?</li><li>Why is duck typing useful?</li><li>How is a protocol different from a plain class?</li><li>When would you use an ABC?</li></ul><h2 id="short-exam-answer" tabindex="-1">Short exam answer <a class="header-anchor" href="#short-exam-answer" aria-label="Permalink to &quot;Short exam answer&quot;">​</a></h2><p>Protocols and shared behavior let Python code work with many different types as long as those types provide the same methods. Duck typing uses behavior directly, while <code>Protocol</code> and <code>ABC</code> make the expected behavior more explicit.</p><hr><p><a href="./Module-12">← Previous: Module 12</a> · <a href="./README">Subject index</a> · <a href="./Module-14">Next: Module 14 →</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/programming-from-first-principles/Module-13.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Module13 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Module13 as default
};
