import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Module 11: Recursion","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/programming-from-first-principles/Module-11.md","filePath":"notes/first-semester/programming-from-first-principles/Module-11.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/programming-from-first-principles/Module-11.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="module-11-recursion" tabindex="-1">Module 11: Recursion <a class="header-anchor" href="#module-11-recursion" aria-label="Permalink to &quot;Module 11: Recursion&quot;">​</a></h1><p><a href="./Module-10">← Previous: Module 10</a> · <a href="./README">Subject index</a> · <a href="./Module-12">Next: Module 12 →</a></p><h2 id="learning-outcomes" tabindex="-1">Learning outcomes <a class="header-anchor" href="#learning-outcomes" aria-label="Permalink to &quot;Learning outcomes&quot;">​</a></h2><ul><li>write a recursive Python function;</li><li>explain base case and recursive case;</li><li>trace a recursion step by step;</li><li>decide when recursion is a good fit.</li></ul><h2 id="prerequisites" tabindex="-1">Prerequisites <a class="header-anchor" href="#prerequisites" aria-label="Permalink to &quot;Prerequisites&quot;">​</a></h2><p>Read <a href="./Module-10">Module 10</a> first. You should understand concrete and generic types.</p><h2 id="the-idea-in-one-sentence" tabindex="-1">The idea in one sentence <a class="header-anchor" href="#the-idea-in-one-sentence" aria-label="Permalink to &quot;The idea in one sentence&quot;">​</a></h2><p>Recursion solves a problem by calling the same function on a smaller version of the problem.</p><h2 id="everyday-analogy" tabindex="-1">Everyday analogy <a class="header-anchor" href="#everyday-analogy" aria-label="Permalink to &quot;Everyday analogy&quot;">​</a></h2><p>Think of a set of nested boxes. To find the smallest item, you open one box, then the smaller box inside it, then the smaller one inside that.</p><h2 id="syntax" tabindex="-1">Syntax <a class="header-anchor" href="#syntax" aria-label="Permalink to &quot;Syntax&quot;">​</a></h2><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> factorial</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(n):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> n </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">==</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 0</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">        return</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 1</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> n </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> factorial(n </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span></code></pre></div><h2 id="worked-example" tabindex="-1">Worked example <a class="header-anchor" href="#worked-example" aria-label="Permalink to &quot;Worked example&quot;">​</a></h2><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">factorial(</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">3</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 3 * factorial(2)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 3 * 2 * factorial(1)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 3 * 2 * 1 * factorial(0)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 6</span></span></code></pre></div><p>Step by step:</p><ol><li><code>factorial(3)</code> needs <code>3 * factorial(2)</code>.</li><li><code>factorial(2)</code> needs <code>2 * factorial(1)</code>.</li><li><code>factorial(1)</code> needs <code>1 * factorial(0)</code>.</li><li><code>factorial(0)</code> returns <code>1</code>.</li><li>The results combine back to <code>6</code>.</li></ol><h2 id="why-this-matters-in-practice" tabindex="-1">Why this matters in practice <a class="header-anchor" href="#why-this-matters-in-practice" aria-label="Permalink to &quot;Why this matters in practice&quot;">​</a></h2><ul><li>In college notes, recursion shows how one problem can be broken into smaller ones.</li><li>In real code, it is common in trees, folder traversal, and divide-and-conquer algorithms.</li><li>It gives a clean way to describe nested or self-similar data.</li></ul><h2 id="important-concepts" tabindex="-1">Important concepts <a class="header-anchor" href="#important-concepts" aria-label="Permalink to &quot;Important concepts&quot;">​</a></h2><h3 id="base-case" tabindex="-1">Base case <a class="header-anchor" href="#base-case" aria-label="Permalink to &quot;Base case&quot;">​</a></h3><p>The base case stops the recursion.</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">if</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> n </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">==</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 0</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 1</span></span></code></pre></div><h3 id="recursive-case" tabindex="-1">Recursive case <a class="header-anchor" href="#recursive-case" aria-label="Permalink to &quot;Recursive case&quot;">​</a></h3><p>The recursive case makes the problem smaller.</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> n </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> factorial(n </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 1</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span></code></pre></div><h3 id="structural-recursion" tabindex="-1">Structural recursion <a class="header-anchor" href="#structural-recursion" aria-label="Permalink to &quot;Structural recursion&quot;">​</a></h3><p>Structural recursion follows the shape of the data, such as a list.</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> total</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(items):</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> not</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> items:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">        return</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 0</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> items[</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">] </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">+</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> total(items[</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">1</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:])</span></span></code></pre></div><h2 id="technical-meaning" tabindex="-1">Technical meaning <a class="header-anchor" href="#technical-meaning" aria-label="Permalink to &quot;Technical meaning&quot;">​</a></h2><p>Recursion is a way to define a computation in terms of itself. The program must always make progress toward a stopping case, or it will keep calling itself forever.</p><h2 id="memory-rule" tabindex="-1">Memory rule <a class="header-anchor" href="#memory-rule" aria-label="Permalink to &quot;Memory rule&quot;">​</a></h2><ul><li>base case = stop</li><li>recursive case = smaller problem</li><li>no base case = infinite recursion</li></ul><h2 id="quick-check" tabindex="-1">Quick check <a class="header-anchor" href="#quick-check" aria-label="Permalink to &quot;Quick check&quot;">​</a></h2><ul><li>What is the base case for factorial?</li><li>Why does recursion need a smaller input?</li><li>When might Python recursion be a poor choice?</li><li>What makes recursion structural?</li></ul><h2 id="short-exam-answer" tabindex="-1">Short exam answer <a class="header-anchor" href="#short-exam-answer" aria-label="Permalink to &quot;Short exam answer&quot;">​</a></h2><p>Recursion is a technique where a function solves a problem by calling itself on a smaller version of the same problem. A recursive function needs a base case to stop and a recursive case to move toward that stop. It is useful for nested or self-similar data.</p><hr><p><a href="./Module-10">← Previous: Module 10</a> · <a href="./README">Subject index</a> · <a href="./Module-12">Next: Module 12 →</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/programming-from-first-principles/Module-11.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Module11 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Module11 as default
};
