import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Module 5 Article: SQL as the Working Language of DBMS","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/persistent-data-management/Articles/Module-5-Article.md","filePath":"notes/first-semester/persistent-data-management/Articles/Module-5-Article.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/persistent-data-management/Articles/Module-5-Article.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="module-5-article-sql-as-the-working-language-of-dbms" tabindex="-1">Module 5 Article: SQL as the Working Language of DBMS <a class="header-anchor" href="#module-5-article-sql-as-the-working-language-of-dbms" aria-label="Permalink to &quot;Module 5 Article: SQL as the Working Language of DBMS&quot;">​</a></h1><h2 id="why-sql-matters" tabindex="-1">Why SQL matters <a class="header-anchor" href="#why-sql-matters" aria-label="Permalink to &quot;Why SQL matters&quot;">​</a></h2><p>SQL is the language you use in real databases every day. It combines schema definition, data manipulation, querying, permissions, and transaction control.</p><h2 id="the-major-categories" tabindex="-1">The major categories <a class="header-anchor" href="#the-major-categories" aria-label="Permalink to &quot;The major categories&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Category</th><th>Purpose</th><th>Examples</th></tr></thead><tbody><tr><td>DDL</td><td>Define structure</td><td><code>CREATE</code>, <code>ALTER</code>, <code>DROP</code></td></tr><tr><td>DML</td><td>Change rows</td><td><code>INSERT</code>, <code>UPDATE</code>, <code>DELETE</code></td></tr><tr><td>DQL</td><td>Read rows</td><td><code>SELECT</code></td></tr><tr><td>DCL</td><td>Control access</td><td><code>GRANT</code>, <code>REVOKE</code></td></tr><tr><td>TCL</td><td>Control transactions</td><td><code>COMMIT</code>, <code>ROLLBACK</code></td></tr></tbody></table><h2 id="joins-and-subqueries" tabindex="-1">Joins and subqueries <a class="header-anchor" href="#joins-and-subqueries" aria-label="Permalink to &quot;Joins and subqueries&quot;">​</a></h2><p>Most SQL exam questions rely on joins. If data lives in two tables, join them using the shared key.</p><p>Subqueries help when one result becomes the input to another condition.</p><p>Example pattern:</p><div class="language-sql vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">sql</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> Name</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Student</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> DepartmentID </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">IN</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    SELECT</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> DepartmentID</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    FROM</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> Department</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    WHERE</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> DepartmentName </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;Computer Science&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">);</span></span></code></pre></div><h2 id="views" tabindex="-1">Views <a class="header-anchor" href="#views" aria-label="Permalink to &quot;Views&quot;">​</a></h2><p>A view is a virtual table based on a query. It is useful for:</p><ul><li>simplifying complex queries</li><li>hiding sensitive columns</li><li>presenting different user-specific views</li></ul><h2 id="stored-procedures-and-triggers" tabindex="-1">Stored procedures and triggers <a class="header-anchor" href="#stored-procedures-and-triggers" aria-label="Permalink to &quot;Stored procedures and triggers&quot;">​</a></h2><p>A stored procedure is a saved program inside the DBMS. It is useful for repeated business logic.</p><p>A trigger runs automatically in response to an event such as insert, update, or delete. Triggers are often used for auditing and enforcing business rules.</p><h2 id="cursors" tabindex="-1">Cursors <a class="header-anchor" href="#cursors" aria-label="Permalink to &quot;Cursors&quot;">​</a></h2><p>Cursors process query results row by row. They are less common than set-based SQL, but they appear in procedural database programming and exam questions.</p><h2 id="best-practice-mindset" tabindex="-1">Best practice mindset <a class="header-anchor" href="#best-practice-mindset" aria-label="Permalink to &quot;Best practice mindset&quot;">​</a></h2><p>SQL should be:</p><ul><li>readable</li><li>consistent</li><li>constrained by keys and checks</li><li>tested with small data before large changes</li></ul><h2 id="exam-tip" tabindex="-1">Exam tip <a class="header-anchor" href="#exam-tip" aria-label="Permalink to &quot;Exam tip&quot;">​</a></h2><p>When writing SQL in an exam, always show:</p><ol><li>Table names</li><li>Join condition</li><li>Filter condition</li><li>Grouping condition if needed</li><li>Output columns</li></ol><p>That makes your query easier to follow and reduces mistakes.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/persistent-data-management/Articles/Module-5-Article.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Module5Article = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Module5Article as default
};
