import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Module 14: Polymorphism","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/programming-from-first-principles/Module-14.md","filePath":"notes/first-semester/programming-from-first-principles/Module-14.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/programming-from-first-principles/Module-14.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="module-14-polymorphism" tabindex="-1">Module 14: Polymorphism <a class="header-anchor" href="#module-14-polymorphism" aria-label="Permalink to &quot;Module 14: Polymorphism&quot;">​</a></h1><p><a href="./Module-13">← Previous: Module 13</a> · <a href="./README">Subject index</a> · <a href="./MCQ">MCQ practice →</a></p><h2 id="learning-outcomes" tabindex="-1">Learning outcomes <a class="header-anchor" href="#learning-outcomes" aria-label="Permalink to &quot;Learning outcomes&quot;">​</a></h2><ul><li>explain how one function can work with many types;</li><li>read a generic Python example;</li><li>distinguish parametric and behavior-based polymorphism;</li><li>connect polymorphism with reusable code.</li></ul><h2 id="prerequisites" tabindex="-1">Prerequisites <a class="header-anchor" href="#prerequisites" aria-label="Permalink to &quot;Prerequisites&quot;">​</a></h2><p>Read <a href="./Module-13">Module 13</a> first. You should understand protocols and shared behavior.</p><h2 id="the-idea-in-one-sentence" tabindex="-1">The idea in one sentence <a class="header-anchor" href="#the-idea-in-one-sentence" aria-label="Permalink to &quot;The idea in one sentence&quot;">​</a></h2><p>Polymorphism means one piece of code can work in many forms without changing its core logic.</p><h2 id="everyday-analogy" tabindex="-1">Everyday analogy <a class="header-anchor" href="#everyday-analogy" aria-label="Permalink to &quot;Everyday analogy&quot;">​</a></h2><p>Think of a universal remote. The same button press can control a TV, fan, or AC because each device understands the same idea in its own way.</p><h2 id="syntax" tabindex="-1">Syntax <a class="header-anchor" href="#syntax" aria-label="Permalink to &quot;Syntax&quot;">​</a></h2><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> typing </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> TypeVar</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">T </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> TypeVar(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;T&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> first</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(items: list[T]) -&gt; T:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> items[</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span></code></pre></div><h2 id="worked-example" tabindex="-1">Worked example <a class="header-anchor" href="#worked-example" aria-label="Permalink to &quot;Worked example&quot;">​</a></h2><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">first([</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">10</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">20</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">30</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">])</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">first([</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;a&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;b&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;c&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">])</span></span></code></pre></div><p>Step by step:</p><ol><li>The same function is used for numbers.</li><li>The same function is used for text.</li><li>The function logic does not change.</li><li>Only the type of input changes.</li></ol><h2 id="why-this-matters-in-practice" tabindex="-1">Why this matters in practice <a class="header-anchor" href="#why-this-matters-in-practice" aria-label="Permalink to &quot;Why this matters in practice&quot;">​</a></h2><ul><li>In college notes, polymorphism shows how generic code stays reusable.</li><li>In real code, it helps with helper functions, containers, and behavior-based APIs.</li><li>It reduces duplication because one design can serve many types.</li></ul><h2 id="important-concepts" tabindex="-1">Important concepts <a class="header-anchor" href="#important-concepts" aria-label="Permalink to &quot;Important concepts&quot;">​</a></h2><h3 id="parametric-polymorphism" tabindex="-1">Parametric polymorphism <a class="header-anchor" href="#parametric-polymorphism" aria-label="Permalink to &quot;Parametric polymorphism&quot;">​</a></h3><p>Parametric polymorphism uses a type variable such as <code>T</code>.</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> echo</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(value: T) -&gt; T:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> value</span></span></code></pre></div><h3 id="behavior-based-polymorphism" tabindex="-1">Behavior-based polymorphism <a class="header-anchor" href="#behavior-based-polymorphism" aria-label="Permalink to &quot;Behavior-based polymorphism&quot;">​</a></h3><p>Different types can support the same operation.</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">len</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;abc&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">len</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">([</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">1</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">2</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">3</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">])</span></span></code></pre></div><h3 id="generic-function" tabindex="-1">Generic function <a class="header-anchor" href="#generic-function" aria-label="Permalink to &quot;Generic function&quot;">​</a></h3><p>A generic function works with more than one type.</p><div class="language-python vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">python</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">def</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> first</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(items: list[T]) -&gt; T:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> items[</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span></code></pre></div><h2 id="technical-meaning" tabindex="-1">Technical meaning <a class="header-anchor" href="#technical-meaning" aria-label="Permalink to &quot;Technical meaning&quot;">​</a></h2><p>Polymorphism means many forms. In Python, it appears when one function or method works across different types without changing its core logic. This can happen through type variables, shared methods, or operations defined by behavior.</p><h2 id="memory-rule" tabindex="-1">Memory rule <a class="header-anchor" href="#memory-rule" aria-label="Permalink to &quot;Memory rule&quot;">​</a></h2><ul><li>parametric = type variable</li><li>behavior-based = shared operations</li><li>generic = works for more than one type</li></ul><h2 id="quick-check" tabindex="-1">Quick check <a class="header-anchor" href="#quick-check" aria-label="Permalink to &quot;Quick check&quot;">​</a></h2><ul><li>Why is <code>first</code> polymorphic?</li><li>What type does <code>T</code> represent?</li><li>How does Python support many forms of behavior?</li><li>Why is polymorphism useful in reusable code?</li></ul><h2 id="short-exam-answer" tabindex="-1">Short exam answer <a class="header-anchor" href="#short-exam-answer" aria-label="Permalink to &quot;Short exam answer&quot;">​</a></h2><p>Polymorphism means one piece of code can work with many types. In Python, it appears in generic functions that use type variables and in behavior-based code where different objects provide the same operations. It makes programs more reusable and flexible.</p><hr><p><a href="./Module-13">← Previous: Module 13</a> · <a href="./README">Subject index</a> · <a href="./MCQ">MCQ practice →</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/programming-from-first-principles/Module-14.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Module14 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Module14 as default
};
