import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Module 8 Article: Transactions, Serializability, and Recovery","description":"","frontmatter":{},"headers":[],"relativePath":"notes/first-semester/persistent-data-management/Articles/Module-8-Article.md","filePath":"notes/first-semester/persistent-data-management/Articles/Module-8-Article.md","lastUpdated":null}');
const _sfc_main = { name: "notes/first-semester/persistent-data-management/Articles/Module-8-Article.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="module-8-article-transactions-serializability-and-recovery" tabindex="-1">Module 8 Article: Transactions, Serializability, and Recovery <a class="header-anchor" href="#module-8-article-transactions-serializability-and-recovery" aria-label="Permalink to &quot;Module 8 Article: Transactions, Serializability, and Recovery&quot;">​</a></h1><h2 id="the-transaction-idea" tabindex="-1">The transaction idea <a class="header-anchor" href="#the-transaction-idea" aria-label="Permalink to &quot;The transaction idea&quot;">​</a></h2><p>A transaction is a unit of work that should either complete fully or have no effect at all. This is essential for correctness when many users update the same database.</p><h2 id="acid" tabindex="-1">ACID <a class="header-anchor" href="#acid" aria-label="Permalink to &quot;ACID&quot;">​</a></h2><ul><li>Atomicity: all or nothing</li><li>Consistency: rules are preserved</li><li>Isolation: transactions should not interfere incorrectly</li><li>Durability: committed changes survive failure</li></ul><h2 id="transaction-states" tabindex="-1">Transaction states <a class="header-anchor" href="#transaction-states" aria-label="Permalink to &quot;Transaction states&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Active -&gt; Partially committed -&gt; Committed</span></span>
<span class="line"><span>   |              |</span></span>
<span class="line"><span>   v              v</span></span>
<span class="line"><span>Failed --------&gt; Aborted</span></span></code></pre></div><h2 id="serializability" tabindex="-1">Serializability <a class="header-anchor" href="#serializability" aria-label="Permalink to &quot;Serializability&quot;">​</a></h2><p>A schedule is serializable if it is equivalent to some serial execution of the same transactions. This gives correctness with concurrency.</p><p>Conflict serializability is tested using conflicting operations on the same data item where at least one operation is a write.</p><h2 id="recoverability" tabindex="-1">Recoverability <a class="header-anchor" href="#recoverability" aria-label="Permalink to &quot;Recoverability&quot;">​</a></h2><p>Schedules must be recoverable so that if one transaction reads data written by another, the writer must commit first. Otherwise a failure can create invalid committed results.</p><h2 id="recovery-techniques" tabindex="-1">Recovery techniques <a class="header-anchor" href="#recovery-techniques" aria-label="Permalink to &quot;Recovery techniques&quot;">​</a></h2><ul><li>Logging records changes</li><li>Checkpoints reduce recovery work</li><li>Undo reverses uncommitted work</li><li>Redo reapplies committed work if needed</li></ul><h2 id="example-scenario" tabindex="-1">Example scenario <a class="header-anchor" href="#example-scenario" aria-label="Permalink to &quot;Example scenario&quot;">​</a></h2><p>If a bank transfer debits one account and credits another, the transaction must not stop in the middle. If it does, money could disappear or be created incorrectly. That is why atomicity and recovery are so important.</p><h2 id="exam-tip" tabindex="-1">Exam tip <a class="header-anchor" href="#exam-tip" aria-label="Permalink to &quot;Exam tip&quot;">​</a></h2><p>When writing a transaction answer, explain:</p><ol><li>what a transaction is</li><li>why ACID matters</li><li>how serializability ensures correctness</li><li>how logging/checkpointing helps recovery</li></ol></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("notes/first-semester/persistent-data-management/Articles/Module-8-Article.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const Module8Article = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  Module8Article as default
};
